# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Geolett"
  tags:
  - "public"
spec:
  type: "website"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_Geolett"
  title: "Security Champion Geolett"
spec:
  type: "security_champion"
  parent: "land_security_champions"
  members:
  - "dagolav"
  children:
  - "resource:Geolett"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "Geolett"
  links:
  - url: "https://github.com/kartverket/Geolett"
    title: "Geolett på GitHub"
spec:
  type: "repo"
  owner: "security_champion_Geolett"
  dependencyOf:
  - "component:Geolett"
